import json
from functools import lru_cache
from pathlib import Path

from app.models import RecommendationCandidate, Channel, IntentType, JourneyStage

VEHICLE_CATALOG_PATH = Path("data/catalog/vehicles.json")


@lru_cache(maxsize=1)
def vehicle_specs_by_id() -> dict[str, dict]:
    if not VEHICLE_CATALOG_PATH.exists():
        return {}
    payload = json.loads(VEHICLE_CATALOG_PATH.read_text(encoding="utf-8"))
    return {item["id"]: item for item in payload.get("vehicles", [])}


def vehicle_candidates() -> list[RecommendationCandidate]:
    candidates: list[RecommendationCandidate] = []
    for spec in vehicle_specs_by_id().values():
        tags = ["travel", "car rental", "vehicle", spec.get("fuel_type", "gas")]
        if spec.get("awd"):
            tags.append("awd")
        if spec.get("convertible"):
            tags.append("convertible")
        if spec.get("cargo_volume_cu_ft", 0) >= 50:
            tags.append("cargo")
        candidates.append(
            RecommendationCandidate(
                id=spec["id"],
                title=spec["title"],
                type="offer",
                channel=Channel.web,
                description=spec.get("description", ""),
                intent_tags=[IntentType.purchase, IntentType.upgrade],
                journey_tags=[JourneyStage.consideration, JourneyStage.purchase],
                content_tags=tags,
                business_value=0.75,
                margin_weight=0.60,
                inventory_weight=0.70,
                compliance_sensitivity=0.05,
            )
        )
    return candidates


DEFAULT_CANDIDATES = [
    RecommendationCandidate(
        id="vehicle_upgrade_suv",
        title="Premium SUV upgrade",
        type="offer",
        channel=Channel.web,
        description="Offer an SUV upgrade to a traveler showing family-trip or airport-rental behavior.",
        intent_tags=[IntentType.purchase, IntentType.upgrade],
        journey_tags=[JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["travel", "family", "car rental", "upgrade", "suv", "airport"],
        business_value=0.90,
        margin_weight=0.85,
        inventory_weight=0.75,
        compliance_sensitivity=0.10,
    ),
    RecommendationCandidate(
        id="early_booking_discount",
        title="Early booking discount",
        type="offer",
        channel=Channel.web,
        description="Present an early booking discount for users comparing travel or rental options.",
        intent_tags=[IntentType.research, IntentType.purchase],
        journey_tags=[JourneyStage.research, JourneyStage.consideration],
        content_tags=["discount", "travel", "booking", "rental"],
        business_value=0.70,
        margin_weight=0.55,
        inventory_weight=0.90,
        compliance_sensitivity=0.05,
    ),
    RecommendationCandidate(
        id="hotel_reservation_assist",
        title="Hotel reservation assistance",
        type="next_best_action",
        channel=Channel.web,
        description="Guide a visitor looking for hotel availability, room options, and reservation next steps.",
        intent_tags=[IntentType.purchase, IntentType.research],
        journey_tags=[JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["hotel", "reservation", "booking", "room", "stay", "lodging", "availability", "travel"],
        business_value=0.84,
        margin_weight=0.62,
        inventory_weight=0.82,
        compliance_sensitivity=0.05,
    ),
    RecommendationCandidate(
        id="hotel_room_offer",
        title="Personalized hotel room offer",
        type="offer",
        channel=Channel.web,
        description="Show a relevant room or stay offer for a traveler browsing hotel reservation content.",
        intent_tags=[IntentType.purchase, IntentType.research],
        journey_tags=[JourneyStage.research, JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["hotel", "room", "reservation", "offer", "stay", "lodging", "travel", "booking"],
        business_value=0.80,
        margin_weight=0.68,
        inventory_weight=0.78,
        compliance_sensitivity=0.05,
    ),
    RecommendationCandidate(
        id="banking_credit_card_offer",
        title="Personalized credit card offer",
        type="offer",
        channel=Channel.web,
        description="Show a relevant banking product offer for a customer researching credit cards, rewards, or financial products.",
        intent_tags=[IntentType.research, IntentType.purchase],
        journey_tags=[JourneyStage.research, JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["banking", "bank", "credit", "card", "rewards", "finance", "financial", "product", "offer"],
        business_value=0.86,
        margin_weight=0.78,
        inventory_weight=0.70,
        compliance_sensitivity=0.70,
    ),
    RecommendationCandidate(
        id="banking_loan_next_step",
        title="Loan application next step",
        type="next_best_action",
        channel=Channel.web,
        description="Guide a banking customer researching loans, mortgage, eligibility, or application next steps.",
        intent_tags=[IntentType.research, IntentType.purchase],
        journey_tags=[JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["banking", "loan", "mortgage", "eligibility", "application", "finance", "rate", "approval"],
        business_value=0.88,
        margin_weight=0.80,
        inventory_weight=0.65,
        compliance_sensitivity=0.75,
    ),
    RecommendationCandidate(
        id="restaurant_reservation_assist",
        title="Restaurant reservation assistance",
        type="next_best_action",
        channel=Channel.web,
        description="Help a visitor find table availability, cuisine options, and reservation times for a restaurant.",
        intent_tags=[IntentType.purchase, IntentType.research],
        journey_tags=[JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["restaurant", "reservation", "table", "dining", "food", "booking", "availability"],
        business_value=0.76,
        margin_weight=0.55,
        inventory_weight=0.86,
        compliance_sensitivity=0.05,
    ),
    RecommendationCandidate(
        id="restaurant_menu_recommendation",
        title="Personalized menu recommendation",
        type="content",
        channel=Channel.web,
        description="Recommend relevant menu, cuisine, or dining content for a visitor browsing restaurant options.",
        intent_tags=[IntentType.research, IntentType.purchase],
        journey_tags=[JourneyStage.awareness, JourneyStage.research, JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["restaurant", "menu", "food", "cuisine", "dining", "dish", "meal", "recommendation"],
        business_value=0.68,
        margin_weight=0.48,
        inventory_weight=0.80,
        compliance_sensitivity=0.03,
    ),
    RecommendationCandidate(
        id="mobile_restaurant_qr_menu",
        title="Mobile QR menu recommendation",
        type="content",
        channel=Channel.mobile,
        description="Show a mobile-friendly restaurant menu after a visitor scans a QR or barcode at the table.",
        intent_tags=[IntentType.research, IntentType.purchase],
        journey_tags=[JourneyStage.awareness, JourneyStage.research, JourneyStage.consideration, JourneyStage.purchase],
        content_tags=["restaurant", "menu", "mobile", "qr", "barcode", "table", "dining", "food", "cuisine"],
        business_value=0.72,
        margin_weight=0.50,
        inventory_weight=0.82,
        compliance_sensitivity=0.03,
    ),
    RecommendationCandidate(
        id="mobile_restaurant_dish_promo",
        title="New dish and promotion offer",
        type="offer",
        channel=Channel.mobile,
        description="Recommend a new dish, chef special, combo, or limited-time promotion after a diner opens the QR menu at the table.",
        intent_tags=[IntentType.purchase],
        journey_tags=[JourneyStage.consideration, JourneyStage.purchase],
        content_tags=[
            "restaurant",
            "menu",
            "mobile",
            "qr",
            "table",
            "dish",
            "new dish",
            "special",
            "promotion",
            "offer",
            "combo",
            "dining",
            "food",
        ],
        business_value=0.84,
        margin_weight=0.72,
        inventory_weight=0.86,
        compliance_sensitivity=0.03,
    ),
    RecommendationCandidate(
        id="hcp_education_content",
        title="HCP educational content",
        type="content",
        channel=Channel.web,
        description="Recommend approved educational content to healthcare professionals researching clinical information.",
        intent_tags=[IntentType.research],
        journey_tags=[JourneyStage.awareness, JourneyStage.research],
        content_tags=["healthcare", "education", "hcp", "clinical", "diabetes"],
        business_value=0.65,
        margin_weight=0.30,
        inventory_weight=0.50,
        compliance_sensitivity=0.80,
    ),
    RecommendationCandidate(
        id="obesity_product_hcp_education",
        title="Obesity product education for HCPs",
        type="content",
        channel=Channel.web,
        description="Recommend approved obesity product education content for healthcare professionals reviewing therapy information.",
        intent_tags=[IntentType.research],
        journey_tags=[JourneyStage.awareness, JourneyStage.research, JourneyStage.consideration],
        content_tags=[
            "healthcare",
            "hcp",
            "doctor",
            "clinical",
            "obesity",
            "product",
            "therapy",
            "education",
        ],
        business_value=0.82,
        margin_weight=0.45,
        inventory_weight=0.55,
        compliance_sensitivity=0.85,
    ),
    RecommendationCandidate(
        id="chatbot_booking_assist",
        title="Chatbot booking assistant",
        type="next_best_action",
        channel=Channel.chatbot,
        description="Conversational next-best-action for a user asking booking, availability, or support questions.",
        intent_tags=[IntentType.purchase, IntentType.support],
        journey_tags=[JourneyStage.consideration, JourneyStage.purchase, JourneyStage.service],
        content_tags=["chatbot", "conversation", "booking", "support", "availability"],
        business_value=0.78,
        margin_weight=0.50,
        inventory_weight=0.80,
        compliance_sensitivity=0.15,
    ),
    RecommendationCandidate(
        id="iot_device_service_alert",
        title="IoT service alert",
        type="micro_prompt",
        channel=Channel.iot,
        description="Device-triggered micro recommendation based on status, usage, or maintenance signal.",
        intent_tags=[IntentType.support],
        journey_tags=[JourneyStage.service, JourneyStage.retention],
        content_tags=["iot", "device", "sensor", "maintenance", "service", "alert"],
        business_value=0.68,
        margin_weight=0.30,
        inventory_weight=0.60,
        compliance_sensitivity=0.35,
    ),
    RecommendationCandidate(
        id="connected_car_location_assist",
        title="Connected car location assist",
        type="micro_prompt",
        channel=Channel.connected_car,
        description="Vehicle-context prompt such as nearby return location, charging, service, or trip support.",
        intent_tags=[IntentType.support, IntentType.purchase],
        journey_tags=[JourneyStage.service, JourneyStage.purchase],
        content_tags=["connected car", "vehicle", "location", "trip", "return", "service"],
        business_value=0.72,
        margin_weight=0.40,
        inventory_weight=0.65,
        compliance_sensitivity=0.30,
    ),
    RecommendationCandidate(
        id="wearable_health_nudge",
        title="Wearable wellness nudge",
        type="micro_prompt",
        channel=Channel.wearable,
        description="Very short, low-sensitivity wellness or reminder-style message for wearable devices.",
        intent_tags=[IntentType.research, IntentType.support],
        journey_tags=[JourneyStage.awareness, JourneyStage.service],
        content_tags=["wearable", "wellness", "nudge", "reminder", "education"],
        business_value=0.55,
        margin_weight=0.20,
        inventory_weight=0.50,
        compliance_sensitivity=0.75,
    ),
]
